### Authenticate and Capture Token
POST {{host}}/v1/tokens/authentication
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.test("Authentication successful", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
    client.global.set("auth_token", response.body.authentication_token.token);
%}

### ######## YT/SPOTI searches ########

### YouTube Search - Valid Query
GET {{host}}/v1/search/youtube/imagine+dragons-radioactive
Authorization: Bearer {{auth_token}}

> {%
    client.test("Search returns results", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.hasOwnProperty("results"), "Response body missing 'results' key");
        client.assert(response.body.results.length > 0, "No results returned for query");
    });
%}

### YouTube Search - Unauthorized (Should Fail)
GET {{host}}/v1/search/youtube/radiohead

> {%
    client.test("Unauthorized search fails", function() {
        client.assert(response.status === 401, "Expected 401 Unauthorized for missing token");
    });
%}

### Spotify Search - Valid Query
GET {{host}}/v1/search/spotify/imagine+dragons-radioactive
Authorization: Bearer {{auth_token}}

> {%
    client.test("Search returns results", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.hasOwnProperty("results"), "Response body missing 'results' key");
        client.assert(response.body.results.length > 0, "No results returned for query");
    });
%}

### Spotify Search - Unauthorized (Should Fail)
GET {{host}}/v1/search/spotify/radiohead

> {%
    client.test("Unauthorized search fails", function() {
        client.assert(response.status === 401, "Expected 401 Unauthorized for missing token");
    });
%}

######## Recommendation ########

### Get Recommendation
@recommendation_id = 48
GET {{host}}/v1/recommendations/{{recommendation_id}}
Authorization: Bearer {{auth_token}}

######## Reservations ########

### Get Reservation
@reservation_id = 1
GET {{host}}/v1/reservations/{{reservation_id}}

### Authenticate and Capture Token
POST {{host}}/v1/reservations
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "TEST2",
  "start_time": "2026-01-28T21:00:00+01:00",
  "end_time": "2026-01-28T23:00:00+01:00"
}

> {%
    client.test("Authentication successful", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Get Reservation
GET {{host}}/v1/reservations
Authorization: Bearer {{auth_token}}
